version: '3.9'

services:
  mariadb:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MARIADB_ROOT_HOST: "%"
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: zasobar
      MARIADB_USER: user
      MARIADB_PASSWORD: user
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - /tmp/docker/sockets/mariadb:/var/run/mysqld
      - app_db:/var/lib/mysql
volumes:
  app_db:
networks:
  nt_mariadb:
    driver: bridge
