//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type StorageConsumptions struct {
	StorageItemConsumptionID int32 `sql:"primary_key"`
	CreatedAt                time.Time
	UpdatedAt                time.Time
	DeletedAt                *time.Time
	NormalizedAmount         *float64
	Unit                     *string
	StorageItemID            int32
}
