//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Users struct {
	ID            int32 `sql:"primary_key"`
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     *time.Time
	Password      *string
	Email         *string
	Name          *string
	GivenName     *string
	FamilyName    *string
	Picture       *string
	EmailVerified bool
	AuthProvider  int32
}
