//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/mysql"

var StorageItemsQuantity = &struct {
	Mass        mysql.StringExpression
	Length      mysql.StringExpression
	Volume      mysql.StringExpression
	Temperature mysql.StringExpression
	Time        mysql.StringExpression
	Count       mysql.StringExpression
}{
	Mass:        mysql.NewEnumValue("mass"),
	Length:      mysql.NewEnumValue("length"),
	Volume:      mysql.NewEnumValue("volume"),
	Temperature: mysql.NewEnumValue("temperature"),
	Time:        mysql.NewEnumValue("time"),
	Count:       mysql.NewEnumValue("count"),
}
