// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package client

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type StorageItemsQuantity string

const (
	StorageItemsQuantityMass        StorageItemsQuantity = "mass"
	StorageItemsQuantityLength      StorageItemsQuantity = "length"
	StorageItemsQuantityVolume      StorageItemsQuantity = "volume"
	StorageItemsQuantityTemperature StorageItemsQuantity = "temperature"
	StorageItemsQuantityTime        StorageItemsQuantity = "time"
	StorageItemsQuantityCount       StorageItemsQuantity = "count"
)

func (e *StorageItemsQuantity) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StorageItemsQuantity(s)
	case string:
		*e = StorageItemsQuantity(s)
	default:
		return fmt.Errorf("unsupported scan type for StorageItemsQuantity: %T", src)
	}
	return nil
}

type NullStorageItemsQuantity struct {
	StorageItemsQuantity StorageItemsQuantity
	Valid                bool // Valid is true if StorageItemsQuantity is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStorageItemsQuantity) Scan(value interface{}) error {
	if value == nil {
		ns.StorageItemsQuantity, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StorageItemsQuantity.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStorageItemsQuantity) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StorageItemsQuantity), nil
}

type Category struct {
	ID          int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   sql.NullTime
	Title       sql.NullString
	DefaultUnit sql.NullString
	Path        sql.NullString
}

type Migration struct {
	Version string
}

type ProductCategory struct {
	CategoryID int32
	Name       sql.NullString
	Path       sql.NullString
	ParentID   sql.NullInt32
}

type StorageConsumption struct {
	StorageItemConsumptionID int32
	CreatedAt                time.Time
	UpdatedAt                time.Time
	DeletedAt                sql.NullTime
	NormalizedAmount         sql.NullFloat64
	Unit                     sql.NullString
	StorageItemID            int32
}

type StorageItem struct {
	StorageItemID  int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeletedAt      sql.NullTime
	Title          sql.NullString
	StoragePlaceID sql.NullInt32
	CategoryID     sql.NullInt32
	BaselineAmount float64
	CurrentAmount  float64
	Quantity       StorageItemsQuantity
	Unit           string
	ExpirationDate sql.NullTime
	Ean            sql.NullString
}

type StoragePlace struct {
	StoragePlaceID int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeletedAt      sql.NullTime
	Title          sql.NullString
	Code           sql.NullString
}

type User struct {
	ID            int32
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     sql.NullTime
	Password      sql.NullString
	Email         sql.NullString
	Name          sql.NullString
	GivenName     sql.NullString
	FamilyName    sql.NullString
	Picture       sql.NullString
	EmailVerified bool
	AuthProvider  int32
}
