-- Database Schema, generated by zasobar, DO NOT EDIT!

CREATE TABLE `categories` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `title` varchar(250) DEFAULT NULL,
  `default_unit` varchar(50) DEFAULT NULL,
  `path` varchar(250) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=58 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `migrations` (
  `version` varchar(255) COLLATE latin1_bin NOT NULL,
  PRIMARY KEY (`version`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_bin;

CREATE TABLE `product_categories` (
  `category_id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `path` varchar(512) DEFAULT NULL,
  `parent_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`category_id`),
  KEY `product_categories_parent_id` (`parent_id`),
  CONSTRAINT `product_categories_parent_id` FOREIGN KEY (`parent_id`) REFERENCES `product_categories` (`category_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=543704 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `storage_consumptions` (
  `storage_item_consumption_id` int(11) NOT NULL AUTO_INCREMENT,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `normalized_amount` double DEFAULT NULL,
  `unit` varchar(50) DEFAULT NULL,
  `storage_item_id` int(11) NOT NULL,
  PRIMARY KEY (`storage_item_consumption_id`),
  KEY `storage_consumption_storage_item_fk` (`storage_item_id`),
  CONSTRAINT `storage_consumption_storage_item_fk` FOREIGN KEY (`storage_item_id`) REFERENCES `storage_items` (`storage_item_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=25 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `storage_items` (
  `storage_item_id` int(11) NOT NULL AUTO_INCREMENT,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `storage_place_id` int(11) DEFAULT NULL,
  `category_id` int(11) DEFAULT NULL,
  `baseline_amount` double NOT NULL,
  `current_amount` double NOT NULL,
  `quantity` enum('mass','length','volume','temperature','time','count') NOT NULL,
  `unit` varchar(50) NOT NULL,
  `expiration_date` datetime DEFAULT NULL,
  `ean` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`storage_item_id`),
  KEY `storage_item_storage_place_fk` (`storage_place_id`),
  KEY `storage_item_category_fk` (`category_id`),
  CONSTRAINT `storage_item_category_fk` FOREIGN KEY (`category_id`) REFERENCES `categories` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `storage_item_storage_place_fk` FOREIGN KEY (`storage_place_id`) REFERENCES `storage_places` (`storage_place_id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `storage_places` (
  `storage_place_id` int(11) NOT NULL AUTO_INCREMENT,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `code` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`storage_place_id`),
  UNIQUE KEY `code` (`code`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `password` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `given_name` varchar(255) DEFAULT NULL,
  `family_name` varchar(255) DEFAULT NULL,
  `picture` varchar(255) DEFAULT NULL,
  `email_verified` tinyint(1) NOT NULL DEFAULT 0,
  `auth_provider` int(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_user_email` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4;

